### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by M-Gonzalo** [PRTTMPRPHT/node-zpaq#2]
Hi! Let me first say I absolutely love this package, having known and used zpaq the usual way for a while.

Now, I'm trying to use it as a brotli/gzip/deflate replacement (mostly as an exercise now, but it's showing a lot of potential)

But it isn't browser ready, though. For example, is trying to use `Error.captureStackTrace`, which is only available as part of the node API.
This is the only thing missing to be able to make the roundtrip between backend and frontend.

I would love if you could look into this, please. Thanks in advance!!

**Comment by PRTTMPRPHT** [comment]
Hi! Unfortunately, as you have found out, this package has been built exclusively for usage with Node.js.
Due to the natives included (which are also built specifically for the Node APIs) this package will not run in any browser.
If you are required to use it in the browser, your best bet here is to compile the original zpaq to WebAssembly and interface with that.
It's relatively easy to do with Emscripten, I have used this method in the past as well.
https://emscripten.org/index.html
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html

**Comment by M-Gonzalo** [comment]
> Hi! Unfortunately, as you have found out, this package has been built exclusively for usage with Node.js. Due to the natives included (which are also built specifically for the Node APIs) this package will not run in any browser. If you are required to use it in the browser, your best bet here is to compile the original zpaq to WebAssembly and interface with that. It's relatively easy to do with Emscripten, I have used this method in the past as well. [emscripten.org/index.html](https://emscripten.org/index.html) [emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html)

I understand. Would it be possible to ask you a little more later about compilation to WebAssembly and related issues? If any complications arise

**Comment by PRTTMPRPHT** [comment]
Sure! You can find my e-mail on my profile page, feel free to drop me a message any time.
